### ISSUE TITLE
Upload to snap store

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cpeditor#456]
**Is your feature request related to a problem? Please describe.**

It is pretty inconvenient for Ubuntu users to download CP Editor now. AppImage is a pain when it comes to updating.

~~Also I am envy of Arch Linux users who have AUR~~

So I think it would be a good idea to use [snaps](https://snapcraft.io) to publish this software, after that a simple

```bash
snap install cpeditor
```

will do the trick.

**Describe the solution you'd like**

Publish this software to snap.

**Describe alternatives you've considered**
Use a ppa to publish it, ~~but I don't really understand the docs of launchpad...~~

**Additional context**

You can assign this to me and I will publish it (with my own ubuntu one account)

**Comment by coder3101** [comment]
With `linuxdeployqt` program you can automatically gather all necessary Shared objects required by our executable to run.

**Comment by Ravenclaw-OIer** [comment]
It's still a work in progress (why stale?)

**Comment by coder3101** [comment]
Have you reserved the snap name `cpeditor` on snapstore. If so please release it so that I can release it on snap store. Please confirm and release ASAP.

**Comment by coder3101** [comment]
Someone has taken `cpeditor` snap name. I have filed the name claim dispute, lets hope it gets sorted out.

**Comment by coder3101** [comment]
cpeditor has been released to our account. I will start working on this issue now.

**Comment by coder3101** [comment]
I have created the snap package but as it turns out snaps are designed to be confined and run in a sandboxed environment. So they do not have access to `gcc`, `clangd`, `cf` or any other program that user may need to run from within the cpeditor. There is a way to bundle all things required inside snap, I am thinking of including complete gcc-9, python3, jre/jdk, clangd inside the snap. It will likely make it heavy in size but it will also be very friendly since, everything will work out of box.

**Comment by Ravenclaw-OIer** [comment]
@coder3101 **I'm sincerely sorry!**  As I no longer work on CP in general, I rarely go on GitHub nowadays and it seemed that I  *had* reserved the snap name. 

Snaps have a "classic mode" which make it work like traditional packages, maybe you can try that?

**Comment by Ravenclaw-OIer** [comment]
Are there anything I can do now?

**Comment by coder3101** [comment]
> Snaps have a "classic mode" which makes it work like traditional packages, maybe you can try that? 


`--classic` is deemed unsafe and requires special verification before it could be published to snap store. It has a huge list of requirements that must be fulfilled before a classic snap can be published.

**Comment by coder3101** [comment]
> Is there anything I can do now?

I have build the snap for cpeditor but as I said it is does not has access to /usr/ directory so it can't run process like g++, clangd, python etc.

**Comment by coder3101** [comment]
`kde-neon` extension packs all Qt and KF5 dependencies and it does not works with `--classic` snaps. I am able to bundle all the dependencies including but the size of snap becomes 500 MB, at this point I think it is not even worth bundling all the packages inside the snap sandbox. People cannot update gcc/llvm, cannot install python libraries and it clearly breaks the idea of customization by preferences except passing arguments.

**Comment by coder3101** [comment]
Hi 
Can anyone install and check if [this cpeditor classic snap](https://github.com/cpeditor/cpeditor/releases/download/6.7.2/cpeditor_6.9.0_amd64.snap) is working as expected.

You will install it by `sudo snap install <file-name> --dangerous --classic`

**Comment by coder3101** [comment]
Snapcraft.yaml file

```yaml
name: cpeditor
base: core20
grade: stable
confinement: classic
adopt-info: cpeditor

package-repositories:
        - type: apt
          formats: [deb, deb-src]
          components: [main]
          suites: [focal]
          key-id: C65D51784EDC19A871DBDBB710C56D0DE9977759
          url: http://ppa.launchpad.net/beineri/opt-qt-5.15.2-focal/ubuntu

apps:
        cpeditor:
                common-id: cpeditor.desktop
                command: usr/bin/cpeditor
                plugs:
                        - home
                        - opengl
                        - network
                        - network-bind
                        - pulseaudio

parts:
        cpeditor:
                parse-info:
                        - usr/share/metainfo/cpeditor.appdata.xml
                plugin: cmake
                build-packages:
                        - build-essential
                        - qt515base
                        - qt515tools
                        - libgl1-mesa-dev
                stage-packages:
                        - qt515base
                source: https://github.com/cpeditor/cpeditor/releases/download/6.7.2/cpeditor.tar.xz
                cmake-parameters:
                        - -DCMAKE_INSTALL_PREFIX=/usr
                        - -DCMAKE_BUILD_TYPE=Release
                override-prime: |
                        snapcraftctl prime
                        sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/cpeditor.png|g' $SNAPCRAFT_PRIME/usr/share/applications/cpeditor.desktop
```
